### ISSUE TITLE
Settings get stored in a specific language

### ISSUE THREAD

**Issue by adrian-castravete** [gephi/gephi-toolkit#23]
Settings with the **boolean** values stored in the `Workspace_*_previewmodel_xml` files are saved in another language than English.
For example I read „adevărat” for “true” and „fals” for “false”. I'm romanian, and the locale is set to ro_RO.
Now I understand that this may not be the right place to post this, but Gephi has no problem loading the said files; however gephi-toolkit doesn't like it.
The traceback for the error I'm getting is:
```
Exception during conversion.
org.gephi.project.io.GephiFormatException: Gephi failed importing the project.

Exception: IllegalArgumentException : fals
File: org.netbeans.beaninfo.editors.WrappersEditor
Line : 98
	at org.gephi.project.io.LoadTask.run(LoadTask.java:173)
	at com.figshare.gephi.converter.FigshareConverter.readGraph(FigshareConverter.java:31)
	at com.figshare.gephi.converter.ProgramStart.run(ProgramStart.java:27)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: fals
	at org.netbeans.beaninfo.editors.WrappersEditor.setAsText(WrappersEditor.java:98)
	at org.gephi.utils.Serialization.readValueFromText(Serialization.java:99)
	at org.gephi.preview.PreviewModelImpl.readXML(PreviewModelImpl.java:485)
	at org.gephi.preview.PreviewPersistenceProvider.readXML(PreviewPersistenceProvider.java:81)
	at org.gephi.project.io.LoadTask.readWorkspaceChildrenXML(LoadTask.java:298)
	at org.gephi.project.io.LoadTask.run(LoadTask.java:128)
	... 3 more
Caused by: org.netbeans.core.UIExceptions$AnnException: fals
	at org.netbeans.core.UIExceptions$AnnException.findOrCreate(UIExceptions.java:119)
	at org.netbeans.core.UIExceptions.annotateUser(UIExceptions.java:79)
	at org.netbeans.beaninfo.editors.WrappersEditor.setAsText(WrappersEditor.java:105)
	... 8 more
Caused by: 
```

**Comment by eduramiba** [comment]
Thanks for the report! We will open an issue at https://github.com/gephi/gephi/issues for 0.9.2 milestone.

**Comment by eduramiba** [comment]
Fixed in commit https://github.com/gephi/gephi/commit/4a5ae9d81e500ac8b85339b4778ad48560387fd8
