### ISSUE TITLE
ClassCastException when running "simple" example

### ISSUE THREAD

**Issue by tschoellhorn** [gephi/gephi-toolkit#53]
Hi,
I just have upgraded from gephi-toolkit:0.9.2 to gephi-toolkit:0.10.1. Now I have problems running a simple example in my own codebase. My code is the following:

```
 // Init a project - and therefore a workspace
ProjectController pc = Lookup.getDefault().lookup(ProjectController.class);
pc.newProject();
Workspace workspace = pc.getCurrentWorkspace();

//Get models and controllers for this new workspace - will be useful later
GraphModel graphModel = Lookup.getDefault().lookup(GraphController.class).getGraphModel();
PreviewModel model = Lookup.getDefault().lookup(PreviewController.class).getModel();
ImportController importController = Lookup.getDefault().lookup(ImportController.class);
```

Yet, I this stacktrace when executing this code: 

```
java.lang.ClassCastException: class org.gephi.preview.PreviewModelImpl cannot be cast to class org.gephi.project.spi.Model (org.gephi.preview.PreviewModelImpl and org.gephi.project.spi.Model are in unnamed module of loader 'app')
	at org.gephi.project.spi.Controller.getModel(Controller.java:46)
	at org.gephi.preview.PreviewControllerImpl.getModel(PreviewControllerImpl.java:99)
	at org.gephi.preview.PreviewControllerImpl.getModel(PreviewControllerImpl.java:77)
	at org.gephi.project.spi.Controller.getModel(Controller.java:58)
	at org.gephi.preview.PreviewControllerImpl.getModel(PreviewControllerImpl.java:104)
	at org.gephi.preview.PreviewControllerImpl.getModel(PreviewControllerImpl.java:77)
	at wdc.utils.gephi.GephiTest.toolkit(GephiTest.java:84)
```

I am using Java11 and Maven for managing dependencies. 

Any ideas what I am missing here? The more or less same code runs without problems in the gephi-toolkit-demo-project. 

In hope for any help,
Tino

**Comment by tschoellhorn** [comment]
It was a error on my behalf. Sorry. Don't bother with that.
