### ISSUE TITLE
NullPointerException in ForceAtlas2 with a large, filtered graph

### ISSUE THREAD

**Issue by habikilevi** [gephi/gephi-toolkit#56]
Hello!.

I'm encountering a NullPointerException when applying the ForceAtlas2 layout algorithm to a large graph (35,000 nodes, 120,000 edges) in Gephi Toolkit 0.10.1.

**Steps taken**:
1. Coloring: Nodes were colored by type (11 root types).
2. Filtering: Nodes were filtered to leave only the 11 root types.
3. Layout: Contract and Circle algorithms were applied to group the 11 nodes into a circle.
4. Locking and visibility: Nodes were locked and the entire graph was made visible.
5. ForceAtlas2: When applying ForceAtlas2, the error occurs.

**Relevant code**:

```
ForceAtlas2 layout = Lookup.getDefault().lookup(ForceAtlas2Builder.class).buildLayout();
layout.resetPropertiesValues();
layout.setAdjustSizes(true);
layoutController.setLayout(layout);
layoutController.executeLayout();

// Configure layout properties
LayoutProperty[] layoutProperties = layout.getProperties();
for (LayoutProperty layoutProperty : layoutProperties) {
  try {
    System.out.println(layoutProperty.getCanonicalName());
    switch (layoutProperty.getCanonicalName()) {
      // ... List relevant property configuration here ...
      case "ForceAtlas2.threads.name":
        layoutProperty.getProperty().setValue(Integer.parseInt("15"));
        break;
      default:
        break;
    }
  } catch (Exception e) {
    System.err.println("Error modifying property: " + layoutProperty.getCanonicalName());
  }
}

layout.setGraphModel(graphModel);
layout.initAlgo();
layout.goAlgo(); <-- Here is the exception
System.out.println("+ forceAtlas2");

try {
  TimeUnit.SECONDS.sleep(2);
} catch (InterruptedException e) {
  e.printStackTrace();
}

layoutController.stopLayout();
layout.endAlgo();
```

**Error:**

```
Nov 14, 2024 2:45:51 PM org.openide.util.Exceptions printStackTrace

SEVERE: null

java.lang.RuntimeException: Unable to layout ForceAtlas2.

        at org.gephi.layout.plugin.forceAtlas2.ForceAtlas2.goAlgo(ForceAtlas2.java:209)

        at org.gephi.layout.LayoutControllerImpl$LayoutRun.run(LayoutControllerImpl.java:196)

        at org.gephi.utils.longtask.api.LongTaskExecutor$RunningLongTask.call(LongTaskExecutor.java:336)

        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)

        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)

        at java.base/java.lang.Thread.run(Thread.java:1583)

Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot read field "mass" because "n2Layout" is null

        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)

        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)

        at org.gephi.layout.plugin.forceAtlas2.ForceAtlas2.goAlgo(ForceAtlas2.java:207)

        ... 6 more

Caused by: java.lang.NullPointerException: Cannot read field "mass" because "n2Layout" is null

        at org.gephi.layout.plugin.forceAtlas2.ForceFactory$linRepulsion.apply(ForceFactory.java:143)

        at org.gephi.layout.plugin.forceAtlas2.Region.applyForce(Region.java:186)

        at org.gephi.layout.plugin.forceAtlas2.Region.applyForce(Region.java:194)

        at org.gephi.layout.plugin.forceAtlas2.Region.applyForce(Region.java:194)

        at org.gephi.layout.plugin.forceAtlas2.Region.applyForce(Region.java:194)

        at org.gephi.layout.plugin.forceAtlas2.Region.applyForce(Region.java:194)

        at org.gephi.layout.plugin.forceAtlas2.Region.applyForce(Region.java:194)

        at org.gephi.layout.plugin.forceAtlas2.NodesThread.run(NodesThread.java:84)

        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)

        ... 4 more
```

**ForceAtlas2 configurations:**

    Scaling Ratio: 2.0
    Strong Gravity Mode: false
    Gravity: 1.0
    Distributed Attraction: true
    LinLog Mode: false
    Adjust Sizes: true
    Edge Weight Influence: 1.0
    Normalize Edge Weights: false
    Inverted Edge Weights: false
    Jitter Tolerance: 2.0
    Barnes Hut Optimization: false
    Barnes Hut Theta: 1.2
    Threads: 15

**Expected Behavior**:

The ForceAtlas2 layout algorithm should be applied to the provided graph model and arrange the nodes in a visually appealing way.

**Questions**:

- Are there any specific ForceAtlas2 configurations recommended for graphs of this size?
- Are there alternatives to ForceAtlas2 for visualizing large and dense graphs?
- Could it be a problem of insufficient memory?

I would appreciate any suggestions or help to resolve this issue.

**Additional Information**:
- Gephi Toolkit version: 0.10.1
- Operating system: Java21 in Windows11

Thank you for your time!.

**Comment by habikilevi** [comment]
It seems that the error is caused by my code. It's a mismanagement of Layout and LayoutController execution. Changing it to AutoLayout doesn't give me any problem.
